export interface ProductPreview {
  id: number;
  platform: string;
  name: string;
  price: string;
  originalPrice?: string;
  icon: string;
  gradient: string;
  badges: Array<"instant" | "hot" | "sale" | "new">;
  reviews: string;
}

export const categories = [
  { label: "Tout", count: 28, icon: "Gamepad2" },
  { label: "Steam", count: 6, icon: "Monitor" },
  { label: "PlayStation", count: 5, icon: "Gamepad2" },
  { label: "Xbox", count: 4, icon: "Circle" },
  { label: "Free Fire", count: 5, icon: "Flame" },
  { label: "PUBG", count: 4, icon: "Crosshair" },
  { label: "Roblox", count: 3, icon: "Boxes" },
  { label: "Google Play", count: 3, icon: "Smartphone" },
  { label: "iTunes", count: 3, icon: "Apple" },
] as const;

export const products: ProductPreview[] = [
  {
    id: 1,
    platform: "Steam",
    name: "Borderlands 4 Standard Edition(Xbox Series X|S) XBOX LIVE",
    price: "37.900",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant"],
    reviews: "1 243",
  },
  {
    id: 2,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 26,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 25,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 24,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 23,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 22,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 20,
    platform: "Steam",
    name: "Steam Gift Card EUR 20",
    price: "71.500",
    originalPrice: "75.000",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "sale"],
    reviews: "892",
  },
  {
    id: 3,
    platform: "Steam",
    name: "Steam Gift Card EUR 50",
    price: "169.900",
    originalPrice: "178.900",
    icon: "Monitor",
    gradient: "from-[#1b2838] to-[#2a475e]",
    badges: ["instant", "hot"],
    reviews: "2 341",
  },
  {
    id: 4,
    platform: "PlayStation",
    name: "PSN EUR 10 Europe",
    price: "38.500",
    icon: "Gamepad2",
    gradient: "from-[#00439c] to-[#0070d1]",
    badges: ["instant"],
    reviews: "654",
  },
  {
    id: 5,
    platform: "PlayStation",
    name: "PSN EUR 20 Europe",
    price: "72.900",
    icon: "Gamepad2",
    gradient: "from-[#00439c] to-[#0070d1]",
    badges: ["instant", "hot"],
    reviews: "1 087",
  },
  {
    id: 6,
    platform: "Xbox",
    name: "Xbox Gift Card EUR 25",
    price: "94.500",
    icon: "Circle",
    gradient: "from-[#107c10] to-[#1e7a1e]",
    badges: ["instant"],
    reviews: "432",
  },
  {
    id: 7,
    platform: "Free Fire",
    name: "Free Fire 310 Diamants",
    price: "17.500",
    icon: "Flame",
    gradient: "from-[#ff6b00] to-[#ff9a00]",
    badges: ["instant", "hot"],
    reviews: "3 201",
  },
  {
    id: 8,
    platform: "Free Fire",
    name: "Free Fire 720 Diamants",
    price: "34.900",
    originalPrice: "36.700",
    icon: "Flame",
    gradient: "from-[#ff6b00] to-[#ff9a00]",
    badges: ["instant", "sale"],
    reviews: "5 420",
  },
  {
    id: 9,
    platform: "PUBG",
    name: "PUBG 600 UC",
    price: "24.900",
    originalPrice: "26.200",
    icon: "Crosshair",
    gradient: "from-[#c8a240] to-[#e8b840]",
    badges: ["instant", "sale"],
    reviews: "987",
  },
  {
    id: 10,
    platform: "Roblox",
    name: "Roblox 800 Robux",
    price: "14.900",
    icon: "Boxes",
    gradient: "from-[#cc0000] to-[#ee3333]",
    badges: ["instant", "new"],
    reviews: "2 109",
  },
  {
    id: 11,
    platform: "Google Play",
    name: "Google Play EUR 15",
    price: "55.500",
    icon: "Smartphone",
    gradient: "from-[#4285f4] to-[#34a853]",
    badges: ["instant"],
    reviews: "543",
  },
  {
    id: 12,
    platform: "iTunes",
    name: "iTunes EUR 15 Europe",
    price: "56.900",
    icon: "Apple",
    gradient: "from-[#555555] to-[#888888]",
    badges: ["instant"],
    reviews: "321",
  },
];

export const subscriptions = [
  { name: "Xbox Game Pass Ultimate", price: "24.900", icon: "BadgeCheck" },
  { name: "PlayStation Plus Essential", price: "28.900", icon: "Gamepad2" },
  { name: "Nintendo Switch Online", price: "14.900", icon: "BadgeCheck" },
  { name: "EA Play Pro", price: "18.900", icon: "BadgeCheck" },
  { name: "World of Warcraft", price: "19.500", icon: "BadgeCheck" },
  { name: "Final Fantasy XIV", price: "16.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
  { name: "Tibia Coins", price: "12.900", icon: "BadgeCheck" },
] as const;

export const steamCards = [
  {
    name: "Steam EUR 5",
    price: "18.900",
    icon: "Monitor",
    badge: "Instant",
    gradient: "from-[#1b2838] to-[#2a475e]",
  },
  {
    name: "Steam EUR 10",
    price: "37.900",
    icon: "Gamepad2",
    badge: "Populaire",
    gradient: "from-[#0f2027] to-[#2c5364]",
  },
  {
    name: "Steam EUR 20",
    price: "71.500",
    icon: "Trophy",
    badge: "-5%",
    gradient: "from-[#360033] to-[#0b8793]",
  },
  {
    name: "Steam EUR 50",
    price: "169.900",
    icon: "Gem",
    badge: "Top",
    gradient: "from-[#1a1a2e] to-[#0f3460]",
  },
  {
    name: "Steam EUR 100",
    price: "334.000",
    icon: "Crown",
    badge: "Premium",
    gradient: "from-[#000428] to-[#004e92]",
  },
  {
    name: "Steam EUR 150",
    price: "499.000",
    icon: "Sparkles",
    badge: "Best value",
    gradient: "from-[#0a0a0a] to-[#1a0533]",
  },
] as const;

export const topGames = [
  {
    rank: 1,
    name: "Call of Duty: Modern Warfare III",
    platform: "PC / PS5 / Xbox",
    price: "189.900",
    icon: "Gamepad2",
  },
  {
    rank: 2,
    name: "Elden Ring",
    platform: "PC / PS5 / Xbox",
    price: "159.900",
    icon: "Sword",
  },
  {
    rank: 3,
    name: "Batman Arkham Knight",
    platform: "PC / PS4",
    price: "34.900",
    icon: "Shield",
  },
  {
    rank: 4,
    name: "Forza Horizon 5",
    platform: "PC / Xbox",
    price: "129.900",
    icon: "Car",
  },
  {
    rank: 5,
    name: "Resident Evil 4 Remake",
    platform: "PC / PS5",
    price: "149.900",
    icon: "Skull",
  },
  {
    rank: 6,
    name: "God of War Ragnarok",
    platform: "PS5 / PS4",
    price: "179.900",
    icon: "Waves",
  },
] as const;

export const paymentMethods = [
  { name: "D17", type: "Mobile pay", icon: "Smartphone" },
  { name: "Flouci", type: "Mobile pay", icon: "Wallet" },
  { name: "e-Dinar", type: "La Poste TN", icon: "BadgeDollarSign" },
  { name: "Virement", type: "Banque", icon: "Landmark" },
  { name: "Visa", type: "Carte", icon: "CreditCard" },
  { name: "Mastercard", type: "Carte", icon: "CreditCard" },
  { name: "PayPal", type: "En ligne", icon: "CircleDollarSign" },
  { name: "WhatsApp", type: "Manuel", icon: "MessageCircle" },
] as const;
